# Generated by Django 6.0.5 on 2026-05-28 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название книги')),
                ('author', models.CharField(max_length=50, verbose_name='Автор книги')),
                ('genre', models.CharField(max_length=20, verbose_name='Жанр книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('publication_year', models.PositiveIntegerField(verbose_name='Год издания книги')),
                ('pages', models.PositiveIntegerField(verbose_name='Количество страниц в книге')),
                ('publisher', models.CharField(max_length=50, verbose_name='Издательство книги')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1, verbose_name='Рейтинг книги')),
                ('cover', models.ImageField(blank=True, upload_to='books/', verbose_name='Обложка книги')),
                ('reservation_limit', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Книгу',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
