# Generated by Django 6.0.5 on 2026-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг книги'),
        ),
    ]
