# Generated by Django 6.0.5 on 2026-06-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
