# Generated by Django 6.0.5 on 2026-06-08 11:48

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО: ')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона: ')),
                ('date_of_birth', models.DateField()),
                ('desired_position', models.CharField(max_length=100, verbose_name='Желаемая должность: ')),
                ('education', models.CharField(max_length=50, verbose_name='Образование: ')),
                ('work_experience', models.CharField(max_length=300, verbose_name='Опыт работы: ')),
                ('skills', models.CharField(max_length=100, verbose_name='Навыки: ')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
