# Generated by Django 6.0.5 on 2026-06-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='resumes',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
