# Generated by Django 6.0.5 on 2026-06-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customRegistration', '0002_customuser_resumes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='resumes',
        ),
    ]
