# Generated by Django 6.0.5 on 2026-06-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customRegistration', '0003_remove_customuser_resumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
