# Generated by Django 6.0.5 on 2026-06-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название жанра')),
                ('description', models.TextField(max_length=300, verbose_name='Описание жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('photo', models.ImageField(upload_to='movies/')),
                ('description', models.TextField(max_length=300, verbose_name='Описание фильма')),
                ('release_date', models.DateField(verbose_name='Дата релиза фильма')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность фильма (в минутах)')),
                ('language', models.CharField(max_length=50, verbose_name='Язык фильма')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг')),
                ('trailer_url', models.URLField(blank=True, verbose_name='Ссылка на трейлер')),
                ('age_rating', models.CharField(max_length=5, verbose_name='Возрастное ограничение')),
                ('genre', models.ManyToManyField(to='CineBoard.genre')),
            ],
        ),
    ]
