# Generated by Django 6.0.5 on 2026-06-01 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(max_length=300, verbose_name='Описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Кличка лошади')),
                ('breed', models.TextField(max_length=50, verbose_name='Порода лошади')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст лошади')),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=300, verbose_name='Описание лошади')),
                ('photo', models.ImageField(blank=True, upload_to='horses/', verbose_name='Изображение лошади')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, verbose_name='Имя заказчика')),
                ('surname', models.TextField(max_length=30, verbose_name='Фамилия заказчика')),
                ('phone', models.CharField(verbose_name='Номер телефона заказчика')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст заказчика')),
                ('horse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='horse_tour.horse')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название тура')),
                ('description', models.TextField(verbose_name='Описание тура')),
                ('price', models.PositiveIntegerField(verbose_name='Цена тура')),
                ('duration', models.CharField(verbose_name='Длительность тура')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='horse_tour.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, verbose_name='Оценка')),
                ('text', models.TextField(blank=True, verbose_name='Описание к оценке')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='horse_tour.tour')),
            ],
        ),
    ]
