# Generated by Django 6.0.5 on 2026-06-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0002_remove_horse_is_available_alter_review_tour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='horse',
            options={'verbose_name': 'Лошадь', 'verbose_name_plural': 'Лошадей'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Клиента', 'verbose_name_plural': 'Клиентов'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона заказчика'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='Длительность тура'),
        ),
    ]
