# Generated by Django 6.0.5 on 2026-06-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0003_alter_category_options_alter_horse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
